'use client';
export { useLaboratoryController } from './useLaboratoryController';
export { useCategoryController } from './useCategoryController';
export { useRegisterController } from './useRegisterController';
export { useProductController } from './useProductController';
export { useLoginController } from './useLoginController';
export { useProgressBar } from './useProgressBar';
export { useDialog } from './useDialog';
export { usePoster } from './usePoster';
export { useHeader } from './useHeader';
export { useSearch } from './useSearch';
export { usePhoto } from './usePhoto';
export { useModal } from './useModal';
export { useTab } from './useTab';
