export type {
 dialogSetting,
 ModalSetting,
 resposeApi,
 typesForm,
 Message,
 Search,
 Photo,
 Item,
} from './common.types';
export type {
 CustomLaboratoryFormProps,
 CustomCategoryFormProps,
 CustomProgressBarProps,
 CustomProductFormProps,
 CustomSearchFormProps,
 CustomButtonIconProps,
 CustomLoadingProps,
 CustomSelectProps,
 CustomDialogProps,
 CustomButtonProps,
 CustomHeaderProps,
 CustomInputProps,
 CustomPhotoProps,
 CustomModalProps,
 CustomListProps,
 CustomItemProps,
 PosterProps,
 IconProps,
} from './component.types';
