import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { NextAuthProvider } from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
 title: 'Little bit red car',
 description: 'Generated by piguavesof.com',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
 return (
  <NextAuthProvider>
   <html lang="en">
    <body className={inter.className}>{children}</body>
   </html>
  </NextAuthProvider>
 );
}
